### ISSUE TITLE
TGT compatibility

### ISSUE THREAD

**Issue by versvs** [hugojcastro/HearthStoneHelper#2]
Before starting, thanks for this piece of software.

I'll use english as I don't know what's the preference for issues in this project. We can continue in spanish if it were the case.

With the availibility of the The Grand Tournament set, the helper stopped working.

I started studying the code in order to get it running, and I got json data of the new cards (though that data need rework, it is not a big issue). I wasn't able to find the images. I don't know if you datamined them yourself. I could have crawled them from websites, but they seem to be smaller than the standard size used so far in this project.

Main problems I noticed:

* Images. I don't have them.
* Though I could rework the JSON with the date, I don't know how card data is assigned so that when you request a remote deck from the Internet it identifies the names in that websites with the cards in the database/json file.

I would be glad to help (though my knowledge is limited), moreover if you don't have the time (or the interest) to update it yourself, but would appreciate any guidelines and help.

**Comment by hugojcastro** [comment]
Ah, damn... The day before TGT release I started working on a tool to get all card images for all locales from game client, and I totally forgot about updating this tool at its actual state (which is full TGT compatibility and card images, except for chinese/korean locales). I'll update it throughout the day ^^

My apologies for being so absentminded :_)

PS: btw, I used to get the card images from sites and official FB accounts, but it's too much time consuming (and they required reworking and image editing), so I decided to create a tool for my own. I'll release it soon, because it's almost finished :)

**Comment by versvs** [comment]
Thanks for the fast reply. Let me know if I can help :)
